resolver: https://raw.githubusercontent.com/nikita-volkov/stack-snapshot/a6eaa07968c998552957af3c8ea935dfe4fa10aa/snapshot.yaml
extra-deps:
- git: https://github.com/nikita-volkov/domain
  commit: c9adf86b6fb9182aafafb26739ef87da5c834a1e
